message:
  style: "&7[&eĞšĞŸ&7] &e%player% &7-> &f%msg%"
  vk: true # Ğ´ÑƒĞ±Ğ»Ğ¸Ñ€Ğ¾Ğ²Ğ°Ñ‚ÑŒ Ğ»Ğ¸ ÑĞ¾Ğ¾Ğ±Ñ‰ĞµĞ½Ğ¸Ğµ Ğ¸Ğ· Ñ‡Ğ°Ñ‚Ğ° Ğ² Ğ²Ğº?
  vkmsg: "ğŸ˜ %player% -> %msg%"
vk:
  message: "[VK] %target% -> %msg%"
  peerid:
admins:
  552489709: 'capojkiii'